network:
  ethernets:
    ens3:
      routes:
        - to: 0.0.0.0/0
          via: 192.168.3.1
          metric: 100
          table: 101
        - to: 1.2.3.4/28
          via: 5.6.7.8
          metric: 100
          table: 102
      routing-policy:
        - from: 192.168.3.0/24
          table: 101
        - to: 1.2.3.4/28
          table: 102
